export const coursesOptions = [
  { label: "Accounting", value: "Accounting" },
  { label: "Accounting and Finance", value: "Accounting and Finance" },
  { label: "Aerospace Engineering", value: "Aerospace Engineering" },
  { label: "Architecture", value: "Architecture" },
  { label: "Artificial Intelligence", value: "Artificial Intelligence" },
  { label: "Biomedical Engineering", value: "Biomedical Engineering" },
  {
    label: "Business Administration (General)",
    value: "Business Administration (General)",
  },
  {
    label: "Business Administration - Accounting",
    value: "Business Administration - Accounting",
  },
  {
    label: "Business Administration - Finance",
    value: "Business Administration - Finance",
  },
  {
    label: "Business Administration - Human Resource Management",
    value: "Business Administration - HRM",
  },
  {
    label: "Business Administration - Marketing",
    value: "Business Administration - Marketing",
  },
  { label: "Civil Engineering", value: "Civil Engineering" },
  { label: "Computer Engineering", value: "Computer Engineering" },
  { label: "Computer Science", value: "Computer Science" },
  { label: "Construction Management", value: "Construction Management" },
  { label: "Cybersecurity", value: "Cybersecurity" },
  { label: "Dentistry", value: "Dentistry" },
  { label: "Electrical Engineering", value: "Electrical Engineering" },
  { label: "Information Systems", value: "Information Systems" },
  { label: "Information Technology", value: "Information Technology" },
  { label: "Law", value: "Law" },
  { label: "Mechanical Engineering", value: "Mechanical Engineering" },
  { label: "Nursing", value: "Nursing" },
  { label: "Pharmacy", value: "Pharmacy" },
  { label: "Physiotherapy", value: "Physiotherapy" },
  { label: "Psychology", value: "Psychology" },
  { label: "Public Health", value: "Public Health" },
  { label: "Software Engineering", value: "Software Engineering" },
  {
    label: "Telecommunications Engineering",
    value: "Telecommunications Engineering",
  },
  {
    label: "Tourism and Hospitality Management",
    value: "Tourism and Hospitality Management",
  },
  { label: "Other / Undecided", value: "Other" },
];
